name: test

on:
  push:
    branches: [main]
  pull_request:

jobs:
  unittest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.11", "3.13"]
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python-version }}
      - name: Tests
        run: uv run --locked python -W error::ResourceWarning -m unittest discover -s tests -v
      - name: The package builds
        run: uv build
