name: test

on:
  push:
    branches: [main]
  pull_request:

jobs:
  unittest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.11", "3.13"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Tests
        run: python -W error::ResourceWarning -m unittest -v
      - name: The package builds
        run: |
          python -m pip install --upgrade build
          python -m build
